---
# Provision FreeIPA client Docker container

#################################
# Set up Docker
- name: Pull FreeIPA client docker image
  docker_image:
    name: "{{freeipa_docker_client_image}}"
  register: freeipa_client_docker_image_pull
  tags:
    - setup

# - name: Debug FreeIPA client docker image pull
#   debug:
#     var: freeipa_client_docker_image_pull
#   tags:
#     - setup

- name: Create container network
  docker_network:
    name: c
    driver_options:
      com.docker.network.bridge.name: c
    ipam_options:
      subnet: "{{container_network_cidr}}"
      gateway: "{{container_network_gateway}}"
  tags:
    - setup

#################################
# Set up IPA client DNS

- name: "Add IPA client IP {{freeipa_client_network_addr}} to
         {{fqdn}} zone ipaclient entry"
  ipa_dnsrecord:
    name: ipaclient
    zone: "{{fqdn}}"
    arecord: "{{freeipa_client_network_addr}}"
    state: present
    ipa_host: "{{fqdn}}"
    ipa_user: "{{ipa_user}}"
    ipa_pass: "{{freeipa_admin_password}}"
  delegate_to: localhost
  tags:
    - configure
    - dns

- name: "Add client network reverse zone
            {{container_network_prefix|reverse_zone}}"
  ipa_dnszone:
    idnsname: "{{container_network_prefix|reverse_zone}}"
    state: present
    ipa_host: "{{fqdn}}"
    ipa_user: "{{ipa_user}}"
    ipa_pass: "{{freeipa_admin_password}}"
  delegate_to: localhost
  tags:
    - configure
    - dns

- name: "Add IPA client container PTR to reverse zone
            {{container_network_prefix|reverse_zone}}"
  ipa_dnsrecord:
    name: "{{freeipa_client_network_addr|last_octet}}"
    zone: "{{container_network_prefix|reverse_zone}}"
    ptrrecord: "ipaclient.{{fqdn}}."
    state: exact
    ipa_host: "{{fqdn}}"
    ipa_user: "{{ipa_user}}"
    ipa_pass: "{{freeipa_admin_password}}"
  delegate_to: localhost
  tags:
    - configure
    - dns

#################################
# Install IPA client container

- name: Run FreeIPA client install in Docker container
  docker_container:
    name: ipaclient
    hostname: "ipaclient.{{fqdn}}"
    image: "{{freeipa_docker_client_image}}"
    volumes:
      - "{{data_volume_path}}:{{data_volume_path}}"
      - "{{freeipa_volume_path}}:{{freeipa_volume_path}}"
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    env:
      IPA_SERVER_IP: "{{ip_addr}}"
      IPA_PORT_53_UDP_ADDR: "{{container_network_gateway}}"
      PASSWORD: "{{freeipa_admin_password}}"
      IPA_PORT_80_TCP_ADDR: "{{ip_addr}}"
      IPA_CLIENT_INSTALL_OPTS: "-N --force-join --force --server={{fqdn}}
                                 --fixed-primary --domain={{domain_name}}"
    networks:
      - name: c
        ipv4_address: "{{freeipa_client_network_addr}}"
    purge_networks: yes
    privileged: yes
    detach: yes
    cleanup: yes
    interactive: yes
    tty: yes
    state: started
    recreate: no
    restart: no
    command: "-s"
    etc_hosts: "{
      '{{fqdn}}': '{{ip_addr}}',
      'ipa.{{fqdn}}': '{{freeipa_network_addr}}',
    }"
  register: docker_run
  tags:
    - install


- name: Wait for FreeIPA client install to complete
  shell: "while ! docker logs ipaclient |
              grep -q FreeIPA-enrolled; do sleep 1; done"
  when: docker_run.changed
  tags:
    - install
