---
# Settings for DigitalOcean droplets

# Droplet creation
size_id: "{{hostvars[hostname].size_id|default(default_size_id)}}"
image_id: "{{hostvars[hostname].image_id|default(default_image_id)}}"
region_id: "{{hostvars[hostname].region_id|default(default_region_id)}}"
volume_size: "{{hostvars[hostname].volume_size|default(default_volume_size)}}"

# FQDN
fqdn: "{{hostname}}.{{domain_name}}"
