---
# Create Ansible vault file

- name: Check if Ansible vault file exists
  stat:
    path: ../var/vault.yaml
  register: vault_path_stat

- block:

  - name:  Template group_vars/freeipa/vault.yaml
    template:
      src: vault.yaml.j2
      dest: /tmp/vault.yaml
    register: vault_template

  - name: Create Ansible vault file
    command: "env EDITOR=lib/bin/editor.sh
                  ansible-vault --vault-password-file=.vault_pass
                      create var/vault.yaml"
    args:
      chdir: ..
      creates: var/vault.yaml

  when: not vault_path_stat.stat.exists
