---
# Create Ansible vault file

- name: Ensure .vault_pass file exists
  # Single password, 30 chars long
  command: bash -c "apg -n 1 -m 30 > .vault_pass"
  args:
    chdir: ..
    creates: .vault_pass

- name: Ensure .vault_pass mode is 0600
  file:
    path: ../.vault_pass
    mode: "0600"

- name: Check if Ansible vault file exists
  stat:
    path: ../var/vault.yaml
  register: vault_path_stat

- block:

  - name:  Template group_vars/freeipa/vault.yaml
    template:
      src: vault.yaml.j2
      dest: /tmp/vault.yaml
    register: vault_template

  - name: Create Ansible vault file
    command: "env EDITOR=lib/bin/editor.sh
                  ansible-vault --vault-password-file=.vault_pass
                      create var/vault.yaml"
    args:
      chdir: ..
      creates: var/vault.yaml

  when: not vault_path_stat.stat.exists
