---
#################################
# Update local /etc/hosts
#
# - These run in a loop to avoid concurrency problems with unsafe_writes

- block:

    - name: "Add/update host IP in /etc/hosts"
      lineinfile:
        dest: /etc/hosts
        regexp: " {{hostvars[item]['fqdn']}} "
        state: present
        line: "{{hostvars[item]['ip_addr']}} {{hostvars[item]['fqdn']}} {{item}}"
        unsafe_writes: yes
      become: true
      delegate_to: localhost
      loop: "{{groups['all']}}"
      when:
        - hostvars[hostname]['ip_addr']|default(false)
      run_once: true

    - name: "Remove host IP in /etc/hosts"
      lineinfile:
        dest: /etc/hosts
        regexp: " {{hostvars[item]['fqdn']}} "
        state: absent
        unsafe_writes: yes
      become: true
      delegate_to: localhost
      loop: "{{groups['all']}}"
      when:
        - not (hostvars[hostname]['ip_addr']|default(false))
      run_once: true
