---
#################################
# Update local /etc/hosts

- block:

    - name: "Add/update host IP in /etc/hosts"
      lineinfile:
        dest: /etc/hosts
        regexp: " {{fqdn}} "
        state: present
        line: "{{ip_addr}} {{fqdn}} {{hostname}}"
        unsafe_writes: yes
      become: true
      delegate_to: localhost
