---
# Make ext4 fs on partition and create+start systemd mount unit

# Example playbook entry
#
# - role: mkfs-ext4
#   device:  /dev/disk/by-id/myvol
#   mount_path: /media/myvol

- name:  "Create ext4 fs on device"
  filesystem:
    dev: "{{ item }}"
    fstype: ext4
  with_items:
    - "{{ device }}"
  become: true
  register: mkfs_ext4
  tags:
    - setup

# - name:  Debug create ext4 fs
#   debug:
#     var: mkfs_ext4
#   tags:
#     - setup

- name:  "Add systemd mount unit in /etc/systemd/system"
  template:
    src: fs.mount.j2
    dest: "/etc/systemd/system/{{ item }}"
  with_items:
    - "{{ mount_path|systemd_escape }}.mount"
  become: true
  register: systemd_mount_unit
  tags:
    - setup

# - name:  Debug systemd mount unit
#   debug:
#     var: systemd_mount_unit
#   tags:
#     - setup

- name: "Install {{ mount_path|systemd_escape }}.mount service"
  systemd:
    name: "{{ mount_path|systemd_escape }}.mount"
    daemon_reload: yes
    enabled: yes
  become: true
  tags:
    - setup

- name: "Check {{mount_path}} mount status"
  shell: "grep -q ' {{mount_path|quote}} ' /proc/mounts && echo yes || echo no"
  changed_when: false
  register: mount_check
  tags:
    - setup

- name: "Start {{ mount_path|systemd_escape }}.mount service"
  systemd:
    name: "{{ mount_path|systemd_escape }}.mount"
    state: restarted
  become: true
  when: mount_check.stdout == 'no'
  tags:
    - setup
