---
# Provision and destroy DigitalOcean hosts

- name: provision and destroy DigitalOcean hosts
  hosts: localhost

  vars_prompt:
    # Prompt for hostname if not already defined
    - name: hostname
      prompt: "DigitalOcean hostname (or '-e hostname=host1')"
      private: no

  roles:
    - base
    # coreos must come first to generate cloud-config
    - coreos
    - digitalocean
