---
# Provision DigitalOcean hosts

- name: Provision DigitalOcean hosts
  hosts: coreos
  # This all runs on localhost regardless of whether hosts exist;
  # don't run setup
  gather_facts: False
  connection: local

  vars:
    operation: provision

  roles:
    - base
    # coreos must come first to generate cloud-config
    - coreos
    - digitalocean

- name: Bootstrap ansible on CoreOS
  hosts: coreos
  # No python on host yet; don't run setup
  gather_facts: False
  vars:
    ansible_python_interpreter: /home/core/bin/python

  roles:
    - defunctzombie.coreos-bootstrap
