---
# Initialize ansible
- include: init.yaml

# Provision droplet, bootstrap ansible, configure block storage
- include: provision.yaml

# Install FreeIPA in Docker container
- include: freeipa-install.yaml

# Configure FreeIPA
- include: freeipa-config.yaml

# Configure etcd2 and fleet cluster
- include: etcd2.yaml
