---
# Destroy the whole cluster
#
# Assumes that droplets have already been destroyed

- name: "Refuse to destroy cluster if 'confirm' is not set to 'all'"
  fail: msg="Please set '-e confirm=all' to destroy cluster"
  when: confirm|default('no') != 'all'

- name:  "Destroy cached files in var/"
  file:
    path: "../var/{{item}}"
    state: absent
  with_items:
    # Ansible artifacts
    - "ansible.log"
    - "retries"
    - "cache"
    - "cfssl"
    - "tmp"
    # SSH keys
    - "ssh_id_rsa"
    - "ssh_id_rsa.pub"
    # FreeIPA artifacts
    - "cacert.pem"
    - "docker"
    # Kubernetes artifacts
    - "k8s"
  delegate_to: localhost
  run_once: true

- name: "Kill cached ssh connections"
  shell: "killall ssh || true"
  delegate_to: localhost
  run_once: true
