---
# SSH key

- name: ensure SSH key exists at var/ssh_id_rsa
  command: "ssh-keygen -t rsa -N '' -C 'ansible manager' -f var/ssh_id_rsa"
  args:
    chdir: ..
    creates: var/ssh_id_rsa
  register: create_ssh_key
  delegate_to: localhost
  run_once: true
