---
# DigitalOcean:  droplet destruction tasks


- name: "Refuse to destroy droplet if 'confirm' is not set to 'yes'"
  fail: msg="Please set '-e confirm=yes' to destroy droplet"
  when: confirm|default('no') != 'yes'

- name:  Destroy droplet
  digital_ocean:
    state: absent
    command: droplet
    name: "{{ fqdn }}"
    unique_name: yes
    api_token:  "{{ do_token }}"

- name:  "Destroy ansible cached data in var/cache/{{hostname}}"
  file:
    path: "../var/cache/{{hostname}}"
    state: absent
  delegate_to: localhost

- name:  "Destroy docker certs in {{docker_client_ssl_dir}}"
  file:
    path: "../{{docker_client_ssl_dir}}"
    state: absent
  delegate_to: localhost

- name:  "Destroy data volume {{data_volume_name}}"
  digital_ocean_block_storage:
    volume_name: "{{data_volume_name}}"
    region: "{{ region_id }}"
    state: absent
    command: create
    api_token:  "{{ do_token }}"

- name:  "Destroy freeipa volume {{freeipa_block_storage_name}}"
  digital_ocean_block_storage:
    volume_name: "{{freeipa_block_storage_name}}"
    region: "{{ region_id }}"
    state: absent
    command: create
    api_token:  "{{ do_token }}"
  when: '"freeipa" in group_names'
