---
# DigitalOcean:  droplet destruction tasks


- name: "Refuse to destroy droplet if 'confirm' is not set to 'host' or 'all'"
  fail: msg="Please set '-e confirm=host' to destroy droplet"
  when: confirm|default('no') != 'host' and confirm|default('no') != 'all'

- name:  Destroy droplet
  digital_ocean:
    state: absent
    command: droplet
    name: "{{ fqdn }}"
    unique_name: yes
    api_token:  "{{ do_token }}"

- name:  "Destroy cached files in var/"
  file:
    path: "../var/{{item}}"
    state: absent
  with_items:
    # Ansible cache
    - "cache/{{hostname}}"
    # Ignition config
    - "container_linux_config-{{hostname}}.yaml"
    - "ignition_config-{{hostname}}.json"
  delegate_to: localhost

- name:  "Destroy data volume {{data_volume_name}}"
  digital_ocean_block_storage:
    volume_name: "{{data_volume_name}}"
    region: "{{ region_id }}"
    state: absent
    command: create
    api_token:  "{{ do_token }}"
  # Droplet can take time to be destroyed
  retries: 3
  delay: 1

- name:  "Destroy freeipa volume"
  digital_ocean_block_storage:
    volume_name: "{{item.volume}}"
    region: "{{item.region}}"
    state: absent
    command: create
    api_token:  "{{ do_token }}"
  with_items:
    - volume: "{{freeipa_block_storage_name}}"
      region: "{{ region_id }}"
  # Droplet can take time to be destroyed
  retries: 3
  delay: 1
  when: '"freeipa" in group_names'
