---
# DigitalOcean:  droplet destruction tasks


- name: Refuse to destroy droplet if 'confirm' is not set
  fail: msg="Please set '-e confirm=1' to destroy droplet"
  when: not confirm|default(False)

- name:  Destroy droplet
  digital_ocean:
    state: absent
    command: droplet
    name: "{{ fqdn }}"
    unique_name: yes
    api_token:  "{{ do_token }}"

- name:  Destroy ansible cached data
  file:
    path: "cache/{{hostname}}"
    state: absent
  delegate_to: localhost
