---
- block:

    - name: "Create {{args.ca_name}} sub-CA"
      ipa_ca:
        name: "{{args.ca_name}}"
        ipacasubjectdn: "CN={{item.ca_subject_cn}},O={{kerberos_realm}}"
        description: "{{item.ca_subject_cn}}"
        state: present
        ipa_host: "{{freeipa_master_fqdn}}"
        ipa_user: "{{ipa_user}}"
        ipa_pass: "{{freeipa_admin_password}}"
      with_items:
        - ca_subject_cn: "{{args.ca_subject_cn}}"

    - name: "Add {{args.ca_name}} CA to CA ACLs"
      ipa_caacl:
        name: "{{item}}"
        ca: "{{args.ca_name}}"
        state: present
        ipa_host: "{{freeipa_master_fqdn}}"
        ipa_user: "{{ipa_user}}"
        ipa_pass: "{{freeipa_admin_password}}"
      with_items:
        - "{{user_cert_acl}}"
        - "hosts_services_caIPAserviceCert"

  delegate_to: localhost
  # Run once
  run_once: True
