---
# Create FreeIPA sub-CA

# Usage:
#
# - set_fact:
#     # IPA name for sub-CA
#     ca_name:  "{{my_ca}}"
#     # CA subject CN
#     ca_subject_cn:  "{{my_ca_subject_cn}}"
#
# - include: tasks/ipa_sub_ca.yaml


- block:

    - name: "Create {{ca_name}} sub-CA, subject CN '{{ca_subject_cn}}'"
      ipa_ca:
        name: "{{ca_name}}"
        ipacasubjectdn: "CN={{ca_subject_cn}},O={{kerberos_realm}}"
        description: "{{ca_subject_cn}}"
        state: present
        ipa_host: "{{fqdn}}"
        ipa_user: "{{ipa_user}}"
        ipa_pass: "{{freeipa_admin_password}}"

    - name: "Add {{ca_name}} CA to CA ACL '{{user_cert_acl}}'"
      ipa_caacl:
        name: "{{user_cert_acl}}"
        ca: "{{ca_name}}"
        state: present
        ipa_host: "{{fqdn}}"
        ipa_user: "{{ipa_user}}"
        ipa_pass: "{{freeipa_admin_password}}"

    - name: "Add {{ca_name}} CA to CA ACL 'hosts_services_caIPAserviceCert'"
      ipa_caacl:
        name: "hosts_services_caIPAserviceCert"
        ca: "{{ca_name}}"
        state: present
        ipa_host: "{{fqdn}}"
        ipa_user: "{{ipa_user}}"
        ipa_pass: "{{freeipa_admin_password}}"

  delegate_to: localhost
  run_once: True
