---
#################################
# Configure etcd on CoreOS
#

#
# Add etcdctl command alias
#
- block:

    - name:  "Check if ~core/.bashrc is a symlink"
      stat:
        path: "/home/core/.bashrc"
      register:  bashrc_stat

    - name:  "Delete ~core/.bashrc symlink"
      file:
        path: "/home/core/.bashrc"
        state: absent
      when:  bashrc_stat.stat.islnk

    - name:  "Copy /usr/share/skel/.bashrc to ~core/.bashrc"
      command: "cp /usr/share/skel/.bashrc /home/core/.bashrc"
      when:  bashrc_stat.stat.islnk

    - name:  Add etcdctl command as alias
      lineinfile:
        dest: "/home/core/.bashrc"
        state: present
        insertafter: EOF
        line: "alias etcdctl='sudo {{etcdctl_command}}'"

  tags:
    - etcdctl-alias

#
# Start etcd-member service
#
- block:

    - name:  "Unmask etcd-member.service"
      systemd:
        name: etcd-member
        masked: false
        enabled: true
        daemon_reload: yes
      register:  etcd_initial_mask

    - name:  "Start etcd-member.service"
      systemd:
        name: etcd-member
        enabled: true
        masked: false
        daemon_reload: yes
        state: "{{ etcd_initial_mask.changed | ternary('restarted','started') }}"
      
  become: true
  tags:
    - etcd-start
