---
# Install and configure Docker dependencies

- name: Install python docker API
  pip:
    name: docker
  tags:
    - setup
  environment:
    # Path for python utilities from defunctzombie.coreos-bootstrap
    PATH: "/usr/sbin:/usr/bin:/home/core/bin"
