---

# - include: add-zone.yaml
# Vars: zone

- name: "IPA check {{zone}} zone"
  shell: "{{ipa_exec}} ipa dnszone-show --raw --all {{zone}}
           |& grep -iq 'idnsname={{zone}}' && echo yes || echo no"
  register: ipa_zone_a_check
  changed_when: ipa_zone_a_check.stdout == 'no'
  tags:
    - configure
    - dns

- name: "IPA add {{zone}}"
  shell: "{{ipa_exec}} ipa dnszone-add {{zone}}"
  when: ipa_zone_a_check.changed
  tags:
    - configure
    - dns
