---
# Configure FreeIPA

#################################
# Init Kerberos credentials
- name: Check for kerberos credentials
  shell: "docker exec -i ipaclient klist |& grep -q krbtgt
              && echo 'yes' || echo 'no'"
  changed_when: False
  register: kerb_creds

- name: Obtain kerberos credentials
  shell: "echo {{freeipa_admin_password}} |
              docker exec -i ipaclient kinit admin"
  when: kerb_creds.stdout == 'no'

#################################
# Harden DNS
- name: Restrict DNS recursion
  lineinfile:
    dest: "/media/freeipa/etc/named.conf"
    regexp: "allow-recursion"
    state: present
    line: "        allow-recursion { 127.0.0.1; 10.0.0.0/8; };"
  become: true
  register:  dns_recursion

- name: Restrict DNS zone transfers
  lineinfile:
    dest: "/media/freeipa/etc/named.conf"
    regexp: "allow-transfer"
    insertafter: "allow-recursion"
    state: present
    line: "        allow-transfer { none; };"
  become: true
  register:  dns_transfers

- name: Restart named
  command: "{{ipa_exec}} systemctl restart named-pkcs11.service"
  when: dns_recursion.changed or dns_transfers.changed

- name: Check DNS zone transfers in IPA
  shell:  "{{ipa_exec}} ipa dnszone-show {{domain_name}}
               | grep -q 'Allow transfer. none' && echo 'ok' || echo 'fix'"
  register: ipa_dns_transfers
  changed_when: ipa_dns_transfers.stdout == 'fix'
  when:  hostname == master_host

- name: Disable DNS zone transfers in IPA
  command: "{{ipa_exec}} ipa dnszone-mod {{domain_name}} --allow-transfer='none;'"
  when: ipa_dns_transfers.changed
          and (dns_recursion.changed or dns_transfers.changed)
          and hostname == master_host

#################################
# Harden LDAP

- name: Restrict LDAP anonymous binds
  ldap_attr:
    bind_dn: "cn=Directory Manager"
    bind_pw: "{{freeipa_ds_password}}"
    dn: cn=config
    name: nsslapd-allow-anonymous-access
    server_uri: "ldaps://{{fqdn}}"
    state: exact
    values: rootdse
  delegate_to: localhost

#################################
# Configure httpd
#
# IPA will be behind haproxy later on, so disable http redirect to
# https by disabling these lines in
# /etc/httpd/conf.d/ipa-rewrite.conf:
#
# RewriteCond %{SERVER_PORT}  !^443$
# RewriteCond %{REQUEST_URI}  !^/ipa/(errors|config|crl)
# RewriteCond %{REQUEST_URI}  !^/ipa/[^\?]+(\.js|\.css|\.png|[...])$
# RewriteRule ^/ipa/(.*)      https://host1.example.com/ipa/$1 [L,R=301,NC]

- name: Disable IPA web UI redirect to https 1
  lineinfile:
    dest: /media/freeipa/etc/httpd/conf.d/ipa-rewrite.conf
    regexp: "^(RewriteCond.*SERVER_PORT.*)$"
    state: present
    line: '#\1'
    backrefs: yes
  become: true
  register:  ipa_redirect_1

- name: Disable IPA web UI redirect to https 2
  lineinfile:
    dest: /media/freeipa/etc/httpd/conf.d/ipa-rewrite.conf
    regexp: "^(RewriteCond.*REQUEST_URI.*errors.*)$"
    state: present
    line: '#\1'
    backrefs: yes
  become: true
  register:  ipa_redirect_2

- name: Disable IPA web UI redirect to https 3
  lineinfile:
    dest: /media/freeipa/etc/httpd/conf.d/ipa-rewrite.conf
    regexp: "^(RewriteCond.*REQUEST_URI.*css.*)$"
    state: present
    line: '#\1'
    backrefs: yes
  become: true
  register:  ipa_redirect_3

- name: Disable IPA web UI redirect to https 4
  lineinfile:
    dest: /media/freeipa/etc/httpd/conf.d/ipa-rewrite.conf
    regexp: "(RewriteRule.*ipa.*https://{{fqdn}}.*)$"
    state: present
    line: '#\1'
    backrefs: yes
  become: true
  register:  ipa_redirect_4

- name: Restart httpd
  command: "{{ipa_exec}} systemctl restart httpd.service"
  when: ipa_redirect_1.changed
     or ipa_redirect_2.changed
     or ipa_redirect_3.changed
     or ipa_redirect_4.changed

#################################
# Misc

- name: IPA set default login shell to /bin/bash
  ldap_attr:
    bind_dn: "{{bind_dn}}"
    bind_pw: "{{freeipa_ds_password}}"
    server_uri: "ldaps://{{fqdn}}"
    dn: "cn=ipaConfig,cn=etc,{{domain_dn}}"
    name: ipaDefaultLoginShell
    values: /bin/bash
    state: exact
  delegate_to: localhost
  when:  hostname == master_host

#################################
# Fix up DNS zones

# ipa-server-install erroneously puts container IP into A record
- name: IPA check if ipa-ca.{{domain_name}} points to container IP
  shell: "{{ipa_exec}} ipa dnsrecord-show --raw {{domain_name}} ipa-ca
          | awk -v res=ok '
              /arecord:/ { if ($2 ~ \"{{freeipa_network_prefix}}\") res=$2; }
              END { print res; }'"
  register: ipa_ca_addr
  changed_when: ipa_ca_addr.stdout != 'ok'

- name: IPA delete ipa-ca.{{domain_name}} A record pointing to container IP
  command: "{{ipa_exec}} ipa dnsrecord-del {{domain_name}} ipa-ca
                  --a-rec={{ipa_ca_addr.stdout}}"
  when: ipa_ca_addr.changed

- name: IPA add ipa-ca.{{domain_name}} A record pointing to host IP
  command: "{{ipa_exec}} ipa dnsrecord-add {{domain_name}} ipa-ca
                  --a-rec={{ip_addr}}"
  when: ipa_ca_addr.changed

