---
# Swap tasks
#
# Requires `swap_device` variable

##############################
# Check swap status

- name:  "Get canonical device path of swap_device"
  shell: "readlink -f {{ item }}"
  register: swap_device_canon_cmd
  # Never report "changed"
  changed_when: False  
  with_items:
    - "{{swap_device|quote}}"

- name: Debug canonical device path
  debug:
    var: swap_device_canon_cmd
    verbosity: 1

- name:  "Set swap_device_canon fact"
  set_fact:
    swap_device_canon:  "{{ item }}"
  with_items:
    - "{{ swap_device_canon_cmd.results[0].stdout }}"

- name:  "Check if already swapping to device"
  shell:  "swapon -s | grep -q '{{ item }}'
            && echo 'swapping' || echo 'not swapping'"
  with_items:
    - "{{ swap_device_canon|quote }}"
  register:  swap_status_cmd
  changed_when: False  

- name: Debug swap status
  debug:
    var: swap_status_cmd
    verbosity: 1

- name:  "Set is_swapping fact"
  set_fact:
    is_swapping:  "{{ item }}"
  with_items:
    - "{{ swap_status_cmd.results[0].stdout == 'swapping' }}"

# - name: Debug swap facts
#   debug:
#     msg: "Swap device = {{swap_device_canon}}; is_swapping = {{is_swapping}}"

- block:
    # Stuff to do if the swap device isn't swapping

    - name:  "Format swap partition"
      command: "mkswap {{ item }}"
      with_items:
        - "{{ swap_device_canon }}"
      become: true
      register:  mkswap_cmd

    # - name:  Debug mkswap_cmd
    #   debug:
    #     var:  mkswap_cmd

    - name:  "Start swap device systemd unit"
      systemd:
        name: "{{ item }}"
        enabled: true
        state: "started"
      with_items:
        - "{{swap_device_systemd_unit}}"
      become: true

    - name:  "Verify swapon status of device"
      shell:  "swapon -s | grep -q '{{ item }}'
                && echo 'swapping' || echo 'not swapping'"
      with_items:
        - "{{ swap_device_canon|quote }}"
      register:  verify_swap_status_cmd
      failed_when: verify_swap_status_cmd.stderr == 'not swapping'
      changed_when:  False

    # - name: Debug verify swap status
    #   debug:
    #     var: verify_swap_status_cmd

  when:  "not is_swapping|default(False)"
