---
# Pull the DigitalOcean API key from the environment
do_token: "{{ lookup('env', 'DO_API_KEY') }}"

# DigitalOcean disk device path
block_device_path_template: "/dev/disk/by-id/scsi-0DO_Volume_%s"
