---
# Partition disk
#
# Called from main.yaml, once for each partition
#
# May set these parted mkpart options:
#   fs_type:  default ext4; linux-swap, ...
#   part_start: default 0
#   part_end:  default 100%

- name: Show partition data
  debug:
    msg: "Partition number {{item.number}}"

# - name: Debug create partition inputs
#   debug:
#     var: item

- name: Create partition
  parted:
    align: "{{ align|default('optimal') }}"
    device: "{{ device }}"
    number: "{{ item.number }}"
    state: present
    part_type: "{{ item.part_type|default('primary') }}"
    fs_type: "{{ item.fs_type|default('ext4') }}"
    part_start: "{{ item.part_start|default('0%') }}"
    part_end: "{{ item.part_end|default('100%') }}"
    unit: GiB
  become: true
  register: create_partition

- name: Gather facts
  set_fact:
    partition_map: "{{partition_map|combine(
                         { '%s_%d'%(volume_name, item.number):create_partition })}}"

# - name: debug create partition
#   debug:
#     var: create_partition

