---
# DigitalOcean:  block storage creation and attachment tasks


# - name: debug block storage creation inputs
#   debug:
#     msg: "volume={{volume_name}} region_id={{hostvars[hostname].region_id}}"
#     verbosity: 1

- name: ensure block storage volume <host>_data exists
  digital_ocean_block_storage:
    volume_name: "{{ data_volume_name }}"
    description: "data volume for {{ hostname }}"
    state: present
    command: create
    api_token:  "{{ do_token }}"
    region: "{{ region_id }}"
    block_size: "{{ volume_size }}"
  register: block_storage_volumes

# - name: debug block storage volume creation
#   debug:
#     var: block_storage_volumes
#     verbosity: 3

- name: attach block storage volume <host>_data to droplet
  digital_ocean_block_storage:
    volume_name: "{{ data_volume_name }}"
    state: present
    command: attach
    droplet_id: "{{ droplet_ids[hostname] }}"
    region: "{{ region_id }}"
    api_token:  "{{ do_token }}"
  register: block_storage_attach
