---
# DigitalOcean:  droplet destruction tasks


- name: Refuse to destroy droplet if 'confirm' is not set
  fail: msg="Please set '-e confirm=1' to destroy droplet"
  when: not confirm|default(False)

- name:  destroy droplet
  digital_ocean:
    state: absent
    command: droplet
    name: "{{ fqdn }}"
    unique_name: yes
    api_token:  "{{ do_token }}"

- name:  destroy block storage
  digital_ocean_block_storage:
    state: absent
    command: create
    volume_name: "{{ data_volume_name }}"
    region: "{{ region_id }}"
    api_token:  "{{ do_token }}"
