---
# DigitalOcean:  droplet creation tasks


# - name: debug hostvars[hostname]
#   debug:
#     var: hostvars[hostname]

# - name:  debug user_data
#   debug:
#     msg: "{{ user_data }}"
#     # verbosity: 3

- name: create cluster droplet
  digital_ocean:
    state: present
    command: droplet
    ssh_key_ids: "{{ digitalocean_ssh_key_id }}"
    name: "{{ fqdn }}"
    api_token:  "{{ do_token }}"
    size_id: "{{ size_id }}"
    region_id: "{{ region_id }}"
    image_id: "{{ image_id }}"
    user_data: "{{ user_data }}"
    unique_name: yes
    wait_timeout: 500
  register: do_create

- name:  debug create droplet
  debug:
    var: "do_create"
    # verbosity: 2

- name: save droplet facts
  set_fact:
    droplet_ids:
      # add hostname -> droplet.id; don't clobber whole dict
      "{{ {hostname:do_create.droplet.id}|combine(droplet_ids|default({})) }}"
    droplet_ips:
      "{{ {hostname:do_create.droplet.ip_address}|
              combine(droplet_ips|default({})) }}"

- name:  debug droplet facts
  debug:
    var: "droplet_ips"
