---
# DigitalOcean:  SSH key creation tasks

- name: ensure SSH key exists at ~/.ssh/id_rsa
  user:
    name: "{{ ansible_user_id }}"
    generate_ssh_key: yes
    ssh_key_file: .ssh/id_rsa

- name: ensure SSH key exists at DigitalOcean
  digital_ocean:
    state: present
    command: ssh
    name: my_rsa_ssh_key
    ssh_pub_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    api_token:  "{{ do_token }}"
  register: DO_ssh_key

# - name: debug SSH key ID
#   debug:
#     msg: "SSH key ID is {{ DO_ssh_key.ssh_key.id }}"
#     verbosity: 1

- name: save DigitalOcean SSH key ID
  set_fact:
    digitalocean_ssh_key_id: "{{ DO_ssh_key.ssh_key.id }}"
    digitalocean_ssh_public_key: "{{ DO_ssh_key.ssh_key.public_key }}"
