---

# - include: add-ptr-record.yaml
# Vars: zone, record, ptrrecord

- name: "IPA check {{zone}} reverse zone {{record}} entry
             {{ptrrecord}} PTR record"
  shell: "{{ipa_exec}} ipa dnsrecord-show --raw --all {{zone}} {{record}}
           |& grep -iq 'ptrrecord. {{ptrrecord}}$' && echo yes || echo no"
  register: ipa_record_ptr_check
  changed_when: ipa_record_ptr_check.stdout == 'no'
  tags:
    - configure
    - dns

- name: "IPA add {{zone}} reverse zone {{record}} entry
             {{ptrrecord}} PTR record"
  shell: "{{ipa_exec}} ipa dnsrecord-add {{zone}} {{record}}
             --ptr-rec={{ptrrecord}}"
  when: ipa_record_ptr_check.changed
  tags:
    - configure
    - dns
