---
# Configure FreeIPA

#################################
# Init Kerberos credentials
- name: Check for kerberos credentials
  shell: "docker exec -i ipaclient klist |& grep -q krbtgt
              && echo 'yes' || echo 'no'"
  changed_when: False
  register: kerb_creds
  tags:
    - setup

- name: Obtain kerberos credentials
  shell: "echo {{freeipa_admin_password}} |
              docker exec -i ipaclient kinit admin"
  when: kerb_creds.stdout == 'no'
  tags:
    - setup

#################################
# Harden DNS
- name: Restrict DNS recursion
  lineinfile:
    dest: "/media/freeipa/etc/named.conf"
    regexp: "allow-recursion"
    state: present
    line: "        allow-recursion { 127.0.0.1; 10.0.0.0/8; };"
  become: true
  register:  dns_recursion
  tags:
    - configure

- name: Restrict DNS zone transfers
  lineinfile:
    dest: "/media/freeipa/etc/named.conf"
    regexp: "allow-transfer"
    insertafter: "allow-recursion"
    state: present
    line: "        allow-transfer { none; };"
  become: true
  register:  dns_transfers
  tags:
    - configure

- name: Restart named
  command: "{{ipa_exec}} systemctl restart named-pkcs11.service"
  when: dns_recursion.changed or dns_transfers.changed
  tags:
    - configure

- name: Check DNS zone transfers in IPA
  shell:  "{{ipa_exec}} ipa dnszone-show {{domain_name}}
               | grep -q 'Allow transfer. none' && echo 'ok' || echo 'fix'"
  register: ipa_dns_transfers
  changed_when: ipa_dns_transfers.stdout == 'fix'
  when:  hostname == master_host
  tags:
    - configure

- name: Disable DNS zone transfers in IPA
  command: "{{ipa_exec}} ipa dnszone-mod {{domain_name}} --allow-transfer='none;'"
  when: ipa_dns_transfers.changed
          and (dns_recursion.changed or dns_transfers.changed)
          and hostname == master_host
  tags:
    - configure

#################################
# Harden LDAP

- name: Restrict LDAP anonymous binds
  ldap_attr:
    bind_dn: "cn=Directory Manager"
    bind_pw: "{{freeipa_ds_password}}"
    dn: cn=config
    name: nsslapd-allow-anonymous-access
    server_uri: "ldaps://{{fqdn}}"
    state: exact
    values: rootdse
  delegate_to: localhost
  tags:
    - configure

#################################
# Configure httpd
#
# IPA will be behind haproxy later on, so disable http redirect to
# https by disabling these lines in
# /etc/httpd/conf.d/ipa-rewrite.conf:
#
# RewriteCond %{SERVER_PORT}  !^443$
# RewriteCond %{REQUEST_URI}  !^/ipa/(errors|config|crl)
# RewriteCond %{REQUEST_URI}  !^/ipa/[^\?]+(\.js|\.css|\.png|[...])$
# RewriteRule ^/ipa/(.*)      https://host1.example.com/ipa/$1 [L,R=301,NC]

- name: Disable IPA web UI redirect to https 1
  lineinfile:
    dest: /media/freeipa/etc/httpd/conf.d/ipa-rewrite.conf
    regexp: "^(RewriteCond.*SERVER_PORT.*)$"
    state: present
    line: '#\1'
    backrefs: yes
  become: true
  register:  ipa_redirect_1
  tags:
    - configure

- name: Disable IPA web UI redirect to https 2
  lineinfile:
    dest: /media/freeipa/etc/httpd/conf.d/ipa-rewrite.conf
    regexp: "^(RewriteCond.*REQUEST_URI.*errors.*)$"
    state: present
    line: '#\1'
    backrefs: yes
  become: true
  register:  ipa_redirect_2
  tags:
    - configure

- name: Disable IPA web UI redirect to https 3
  lineinfile:
    dest: /media/freeipa/etc/httpd/conf.d/ipa-rewrite.conf
    regexp: "^(RewriteCond.*REQUEST_URI.*css.*)$"
    state: present
    line: '#\1'
    backrefs: yes
  become: true
  register:  ipa_redirect_3
  tags:
    - configure

- name: Disable IPA web UI redirect to https 4
  lineinfile:
    dest: /media/freeipa/etc/httpd/conf.d/ipa-rewrite.conf
    regexp: "(RewriteRule.*ipa.*https://{{fqdn}}.*)$"
    state: present
    line: '#\1'
    backrefs: yes
  become: true
  register:  ipa_redirect_4
  tags:
    - configure

- name: Restart httpd
  command: "{{ipa_exec}} systemctl restart httpd.service"
  when: ipa_redirect_1.changed
     or ipa_redirect_2.changed
     or ipa_redirect_3.changed
     or ipa_redirect_4.changed
  tags:
    - configure

#################################
# Misc

- name: IPA set default login shell to /bin/bash
  ldap_attr:
    bind_dn: "{{bind_dn}}"
    bind_pw: "{{freeipa_ds_password}}"
    server_uri: "ldaps://{{fqdn}}"
    dn: "cn=ipaConfig,cn=etc,{{domain_dn}}"
    name: ipaDefaultLoginShell
    values: /bin/bash
    state: exact
  delegate_to: localhost
  when:  hostname == master_host
  tags:
    - configure

#################################
# Fix up ipa-ca DNS record
# 
# ipa-server-install erroneously puts container IP into A record

- name: "Prepare to del host IP {{ip_addr}} from {{domain_name}} zone
            ipa-ca entry"
  set_fact:
    zone: "{{domain_name}}"
    record: "ipa-ca"
    arecord: "{{freeipa_network_addr}}"
  tags:
    - configure
    - dns

- include: del-a-record.yaml

- name: "Prepare to add host IP {{ip_addr}} to {{fqdn}} zone ipa-ca entry"
  set_fact:
    zone: "{{domain_name}}"
    record: "ipa-ca"
    arecord: "{{ip_addr}}"
  tags:
    - configure
    - dns

- include: add-a-record.yaml

#################################
# Add host DNS zone and transfer A record

- name: "Prepare to add {{fqdn}} zone"
  set_fact:
    zone: "{{fqdn}}"
  tags:
    - configure
    - dns

- include: add-zone.yaml

- name: "Prepare to del host IP {{ip_addr}} from {{domain_name}} zone
            {{hostname}} entry"
  set_fact:
    zone: "{{domain_name}}"
    record: "{{hostname}}"
    arecord: "{{ip_addr}}"
  tags:
    - configure
    - dns

- include: del-a-record.yaml

- name: "Prepare to add host IP {{ip_addr}} to {{fqdn}} zone @ entry"
  set_fact:
    zone: "{{fqdn}}"
    record: "@"
    arecord: "{{ip_addr}}"
  tags:
    - configure
    - dns

- include: add-a-record.yaml

- name: "Prepare to add IPA container IP {{freeipa_network_addr}}
             to {{fqdn}} zone ipa entry"
  set_fact:
    zone: "{{fqdn}}"
    record: "ipa"
    arecord: "{{freeipa_network_addr}}"
  tags:
    - configure
    - dns

- include: add-a-record.yaml

#################################
# Add host DNS freeipa network reverse zone

- name: "Prepare to add {{freeipa_network_prefix|reverse_zone}} zone"
  set_fact:
    zone: "{{freeipa_network_prefix|reverse_zone}}"
  tags:
    - configure
    - dns

- include: add-zone.yaml

- name: "Prepare to add IPA container PTR record to {{fqdn}} zone"
  set_fact:
    zone: "{{freeipa_network_prefix|reverse_zone}}"
    record: "{{freeipa_network_addr|last_octet}}"
    ptrrecord: "ipa.{{fqdn}}"
  tags:
    - configure
    - dns

- include: add-ptr-record.yaml
