---
# Configure FreeIPA

#################################
# Harden DNS server IPA settings

- name: "Restrict zone transfers for {{domain_name}} in IPA"
  ipa_dnszone:
    idnsname: "{{domain_name}}"
    state: present
    idnsallowtransfer: "none;"
    ipa_host: "{{master_fqdn}}"
    ipa_user: "{{ipa_user}}"
    ipa_pass: "{{freeipa_admin_password}}"
  delegate_to: localhost
  register: create_fqdn_dnszone
  when:  hostname == master_host
  run_once: true
  tags:
    - configure
    - dns

#################################
# Harden LDAP settings

- name: "Restrict LDAP anonymous binds in IPA"
  ldap_attr:
    bind_dn: "cn=Directory Manager"
    bind_pw: "{{freeipa_ds_password}}"
    dn: cn=config
    name: nsslapd-allow-anonymous-access
    server_uri: "ldaps://{{master_fqdn}}"
    state: exact
    values: rootdse
  delegate_to: localhost
  when:  hostname == master_host
  run_once: true
  tags:
    - configure

#################################
# Misc

- name: "Set default login shell to /bin/bash in IPA"
  ldap_attr:
    bind_dn: "{{bind_dn}}"
    bind_pw: "{{freeipa_ds_password}}"
    server_uri: "ldaps://{{master_fqdn}}"
    dn: "cn=ipaConfig,cn=etc,{{domain_dn}}"
    name: ipaDefaultLoginShell
    values: /bin/bash
    state: exact
  delegate_to: localhost
  when:  hostname == master_host
  run_once: true
  tags:
    - configure

#################################
# Fix up ipa-ca DNS record
# 
# ipa-server-install erroneously puts container IP into A record

- block:

    - name: "Remove container IP from ipa-ca A record"
      ipa_dnsrecord:
        name: ipa-ca
        zone: "{{domain_name}}"
        arecord: "{{item}}"
        state: absent
        ipa_host: "{{master_fqdn}}"
        ipa_user: "{{ipa_user}}"
        ipa_pass: "{{freeipa_admin_password}}"
      with_items:
        - "{{freeipa_network_addr}}"

    - name: "Add host IP to ipa-ca A record"
      ipa_dnsrecord:
        name: ipa-ca
        zone: "{{domain_name}}"
        arecord: "{{item}}"
        state: present
        ipa_host: "{{master_fqdn}}"
        ipa_user: "{{ipa_user}}"
        ipa_pass: "{{freeipa_admin_password}}"
      with_items:
        - "{{ip_addr}}"

  delegate_to: localhost
  tags:
    - configure
    - dns

#################################
# Add host DNS zone and transfer A record

- block:

    - name: "Add DNS zone for fqdn"
      ipa_dnszone:
        idnsname: "{{item}}"
        state: present
        ipa_host: "{{master_fqdn}}"
        ipa_user: "{{ipa_user}}"
        ipa_pass: "{{freeipa_admin_password}}"
      with_items:
        - "{{fqdn}}"
      register: create_fqdn_dnszone

    - name: "Remove hostname from {{domain_name}}. zone"
      ipa_dnsrecord:
        name: "{{item}}"
        zone: "{{domain_name}}"
        state: absent
        ipa_host: "{{master_fqdn}}"
        ipa_user: "{{ipa_user}}"
        ipa_pass: "{{freeipa_admin_password}}"
      with_items:
        - "{{hostname}}"

    - name: "Add host IP to [fqdn]. zone A record"
      ipa_dnsrecord:
        name: "@"
        zone: "{{item.zone}}"
        arecord: "{{item.ip_addr}}"
        state: present
        ipa_host: "{{master_fqdn}}"
        ipa_user: "{{ipa_user}}"
        ipa_pass: "{{freeipa_admin_password}}"
      with_items:
        - zone: "{{fqdn}}"
          ip_addr: "{{ip_addr}}"

    - name: "Add IPA container IP to ipa.[fqdn]. zone A record"
      ipa_dnsrecord:
        name: ipa
        zone: "{{item.zone}}"
        arecord: "{{item.ip_addr}}"
        state: present
        ipa_host: "{{master_fqdn}}"
        ipa_user: "{{ipa_user}}"
        ipa_pass: "{{freeipa_admin_password}}"
      with_items:
        - ip_addr: "{{freeipa_network_addr}}"
          zone: "{{fqdn}}"

  delegate_to: localhost
  tags:
    - configure
    - dns

#################################
# Add host DNS freeipa network reverse zone

- block:

    - name: "Add FreeIPA network reverse zone"
      ipa_dnszone:
        idnsname: "{{item}}"
        state: present
        ipa_host: "{{master_fqdn}}"
        ipa_user: "{{ipa_user}}"
        ipa_pass: "{{freeipa_admin_password}}"
      with_items:
        - "{{freeipa_network_prefix|reverse_zone}}"

    - name: "Add IPA container PTR to IPA network reverse zone"
      ipa_dnsrecord:
        name: "{{item.last_octet}}"
        zone: "{{item.zone}}"
        ptrrecord: "{{item.ptr}}"
        state: present
        ipa_host: "{{master_fqdn}}"
        ipa_user: "{{ipa_user}}"
        ipa_pass: "{{freeipa_admin_password}}"
      with_items:
        - last_octet: "{{freeipa_network_addr|last_octet}}"
          zone: "{{freeipa_network_prefix|reverse_zone}}"
          ptr: "ipa.{{fqdn}}"

  delegate_to: localhost
  tags:
    - configure
    - dns

#################################
# Set up CA ACL for IECUserRoles cert profile and add manager user

- block:

    - name: "Create user CA ACL with user cert profile"
      ipa_caacl:
        name: "{{item.ca_acl}}"
        certprofile: "{{item.certprofile}}"
        state: enabled
        ipa_host: "{{master_fqdn}}"
        ipa_user: "{{ipa_user}}"
        ipa_pass: "{{freeipa_admin_password}}"
      with_items:
        - ca_acl: "{{user_cert_acl}}"
          certprofile: "{{user_cert_profile}}"

    - name: "Create manager user"
      # The admin user can't do some things, like create user certs,
      # dunno why, so add a 'manager' user to do it instead
      ipa_user:
        name: "{{manager_id}}"
        state: present
        givenname: Manager
        sn: User
        # password: "{{freeipa_admin_password}}"
        ipa_host: "{{master_fqdn}}"
        ipa_user: "{{ipa_user}}"
        ipa_pass: "{{freeipa_admin_password}}"
      tags: manager-user

    - name: "Add manager user to user CA ACL {{user_cert_acl}}"
      ipa_caacl:
        name: "{{item}}"
        user: "{{manager_id}}"
        state: present
        ipa_host: "{{master_fqdn}}"
        ipa_user: "{{ipa_user}}"
        ipa_pass: "{{freeipa_admin_password}}"
      with_items:
        - "{{user_cert_acl}}"
      tags: manager-user

  delegate_to: localhost
  when:  hostname == master_host
  run_once: True
  tags:
    - ca-acl
    - configure
