---
# Install and run FreeIPA fleet service

- name: Install FreeIPA fleet service ipa@.service
  template:
    src: ipa@.service.j2
    dest: "{{freeipa_volume_path}}/ipa@.service"
  become: true
  when: hostname == master_host

- name: Submit FreeIPA fleet service ipa@.service
  command: "fleetctl submit {{freeipa_volume_path}}/ipa@.service"
  when: hostname == master_host

- name:  Remove FreeIPA container
  docker_container:
    name: ipa
    state: absent

- name: Load FreeIPA fleet service ipa@{{hostname}}.service
  command: "fleetctl load ipa@{{hostname}}.service"

- name: Start FreeIPA fleet service ipa@{{hostname}}.service
  command: "fleetctl start ipa@{{hostname}}.service"
