---
- include: droplet.yaml

- name: DigitalOcean droplets--Create and attach block storage
  hosts: localhost

  vars:
    do_token: "{{ lookup('env', 'DO_API_KEY') }}"
    volume_name: "{{ item|hostname() }}-data"

  tasks:

    # - name: debug block storage creation inputs
    #   debug:
    #     msg: "volume={{volume_name}} region_id={{hostvars[item].region_id}}"
    #     verbosity: 1
    #   with_items: "{{ groups.coreos }}"

    - name: ensure block storage volume <host>_data exists
      digital_ocean_block_storage:
        volume_name: "{{ volume_name }}"
        description: "data volume for {{ item }}"
        state: present
        command: create
        api_token:  "{{ do_token }}"
        region: "{{ hostvars[item].region_id }}"
        block_size: "{{ hostvars[item].volume_size }}"
      with_items: "{{ groups.coreos }}"
      register: block_storage_volumes

    - name: debug block storage volume creation
      debug:
        var: block_storage_volumes
        verbosity: 3

    - name: attach block storage volume to droplet
      digital_ocean_block_storage:
        volume_name: "{{ volume_name }}"
        state: present
        command: attach
        droplet_id: "{{ hostvars.localhost.droplets[item].id }}"
        region: "{{ hostvars[item].region_id }}"
        api_token:  "{{ do_token }}"
      with_items: "{{ groups.coreos }}"
      register: block_storage_attach
