---

- name:  DigitalOcean droplets--Destroy
  hosts: localhost
  gather_facts: no

  vars:
    do_token: "{{ lookup('env', 'DO_API_KEY') }}"
    volume_name: "{{ item }}-data"

  tasks:

    - name:  destroy droplet
      digital_ocean:
        state: absent
        command: droplet
        name: "{{ item }}"
        unique_name: yes
        api_token:  "{{ do_token }}"
      with_items: "{{ groups.coreos }}"

    - name:  destroy block storage
      digital_ocean_block_storage:
        state: absent
        command: create
        volume_name: "{{ volume_name }}"
        region: "{{ hostvars[item].region_id }}"
        api_token:  "{{ do_token }}"
      with_items: "{{ groups.coreos }}"
