---
- name: DigitalOcean--Create SSH keys
  hosts: localhost

  vars:
    do_token: "{{ lookup('env', 'DO_API_KEY') }}"

  tasks:

    - name: ensure SSH key exists at ~/.ssh/id_rsa
      user:
        name: "{{ ansible_user_id }}"
        generate_ssh_key: yes
        ssh_key_file: .ssh/id_rsa

    - name: ensure SSH key exists at DigitalOcean
      digital_ocean:
        state: present
        command: ssh
        name: my_rsa_ssh_key
        ssh_pub_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        api_token:  "{{ do_token }}"
      register: my_rsa_ssh_key

    # - name: debug SSH key ID
    #   debug:
    #     msg: "SSH key ID is {{ my_rsa_ssh_key.ssh_key.id }}"
    #     verbosity: 1
