---
# Provision FreeIPA Docker container

#################################
# Set up Docker
- name: Pull FreeIPA docker image
  docker_image:
    name: "{{freeipa_docker_image}}"
  tags:
    - setup

- name: Create FreeIPA container network
  docker_network:
    name: ipa
    driver_options:
      com.docker.network.bridge.name: "ipa"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.default_bridge: "false"
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"
      com.docker.network.driver.mtu: "1450"
    ipam_options:
      subnet: "{{freeipa_network_cidr}}"
      gateway: "{{freeipa_network_gateway}}"
  tags:
    - setup
    - docker-ipa-network

#################################
# Set up IPA server configuration
- name: Install FreeIPA server config
  template:
    src: ipa-server-install-options.j2
    dest: "{{freeipa_volume_path}}/ipa-server-install-options"
  register: ipa_install_options
  become: true
  when: hostname == master_host
  tags:
    - configure

#################################
# Set up IPA replica configuration
- name: Install FreeIPA replica config
  template:
    src: ipa-replica-install-options.j2
    dest: "{{freeipa_volume_path}}/ipa-replica-install-options"
  register: ipa_install_options
  become: true
  when: hostname != master_host
  tags:
    - configure

- name: Create FreeIPA replica info file on master
  command: "docker exec -i ipa ipa-replica-prepare {{fqdn}}
                 --ip-address {{ip_addr}} --no-reverse"
  delegate_to: "{{master_host}}"
  when: hostname != master_host
  tags:
    - configure

- name: Fetch FreeIPA replica info from master
  fetch:
    src: "{{freeipa_volume_path}}/var/lib/ipa/replica-info-{{fqdn}}.gpg"
    dest: "cache/replica-info-{{fqdn}}.gpg"
  become: true
  delegate_to: "{{master_host}}"
  when: hostname != master_host
  tags:
    - configure

- name: Copy FreeIPA replica info to replica
  copy:
    src: "cache/replica-info-{{fqdn}}.gpg"
    dest: "{{freeipa_volume_path}}/var/lib/ipa/replica-info-{{fqdn}}.gpg"
  become: true
  when: hostname != master_host
  tags:
    - configure

#################################
# Install IPA server/replica
- name:  Check if install is already complete
  stat:
    path: "{{freeipa_volume_path}}/etc/systemd/system/{{ ''
             }}container-ipa.target.wants/ipa-server-upgrade.service"
  register: install_path_stat
  changed_when:  not install_path_stat.stat.exists
  tags:
    - install
    - docker-run-ipa

- name: "Clean out any incomplete prior install"
  # The FreeIPA install doesn't cleanly resume after
  # restarting; deal with it by restarting from scratch
  file:
    state: absent
    path: "{{freeipa_volume_path}}/{{item}}"
  with_items:
    - "build-id"
    - "etc"
    - "hostname"
    - "root"
    - "usr"
    - "var"
  become: true
  when: install_path_stat.changed
  tags:
    - install
    - docker-run-ipa

- name: "Remove any stale ipa container"
  command:  "docker rm ipa"
  failed_when:  false
  register:  docker_rm_ipa
  changed_when:  docker_rm_ipa.rc == 0
  when: install_path_stat.changed
  tags:
    - install
    - docker-run-ipa

- name: "Template ipa.service"
  template:
    src: ipa.service.j2
    dest: "/etc/systemd/system/ipa.service"
  become: true
  register:  ipa_unit_file
  tags:
    - install
    - docker-run-ipa

- name: "Start ipa.service"
  systemd:
    name: ipa.service
    daemon_reload: "{{ ipa_unit_file.changed | ternary('yes','no') }}"
    enabled: true
    state: "{{  (ipa_unit_file.changed or install_path_stat.changed)
                  | ternary('restarted','started') }}"
  register: ipa_service_start
  become: true
  tags:
    - install
    - docker-run-ipa

#
# Wait for install to complete and service to come online
#
- include:  tasks/freeipa-service-wait.yaml
  tags:
    - install
    - docker-run-ipa
