---
# Make ext4 fs on partition and create+start systemd mount unit

# Example playbook entry
#
# - role: mkfs-ext4
#   device:  /dev/disk/by-id/myvol
#   mount_path: /media/myvol

- name:  Create ext4 fs
  filesystem:
    dev: "{{ device }}"
    fstype: ext4
  become: true
  register: mkfs_ext4
  tags:
    - setup

# - name:  Debug create ext4 fs
#   debug:
#     var: mkfs_ext4
#   tags:
#     - setup

- name:  Add systemd mount unit
  template:
    src: fs.mount.j2
    dest: "/etc/systemd/system/{{ mount_path|systemd_escape }}.mount"
  become: true
  register: systemd_mount_unit
  tags:
    - setup

# - name:  Debug systemd mount unit
#   debug:
#     var: systemd_mount_unit
#   tags:
#     - setup

- name: Check mount status
  shell: "grep -q ' {{mount_path|quote}} ' /proc/mounts && echo yes || echo no"
  changed_when: false
  register: mount_check
  tags:
    - setup

- name: Mount filesystem
  systemd:
    name: "{{ mount_path|systemd_escape }}.mount"
    daemon_reload: yes
    state: restarted
  become: true
  when: mount_check.stdout == 'no'
  tags:
    - setup
