---
#################################
# Configure Docker server and client TLS
#
# Enable TLS service on port 2375; afterwards, run docker remotely like this
#
# docker --tlsverify \
#     -H tcp://host1.example.com:2375 \
#     --tlscacert ~/.docker/ca.pem
#     --tlscert ~/.docker/cert.pem
#     --tlskey ~/.docker/key.pem
#
# or
# export DOCKER_HOST=tcp://server.example.com:2376 DOCKER_TLS_VERIFY=1
#
# Instructions for enabling TLS with auth
# https://coreos.com/os/docs/latest/customizing-docker.html#enable-the-remote-api-with-tls-authentication
#
# Docker TLS socket instructions require separate
# `docker-tls-tcp.socket` unit.  Doing it this way requires the docker
# service to be stopped, the docker socket restarted, and the docker
# service started again, or the socket will fail with the following
# error:
#
#     docker-tls-tcp.socket: Socket service docker.service already active, refusing.
#     Failed to listen on Docker Secured Socket for the API.
#
# Interleaved service stopping/starting is complicated in Ansible.
# Instead, just run both the TCP and local socket from the same
# service.  See https://github.com/coreos/bugs/issues/1362
#
# systemd socket unit docs
# https://www.freedesktop.org/software/systemd/man/systemd.socket.html
#
- block:

    - name: "Install docker.socket systemd dropin directory"
      file:
        path: "{{dropin_dir_pat % 'docker.socket'}}"
        state: directory
        mode: 0755

    - name: "Install docker.socket dropin file to add TCP port 2375"
      template:
        src: 10-docker-tcp-socket.conf.j2
        dest: "{{dropin_dir_pat % 'docker.socket'}}/10-docker-tcp-socket.conf"
      register: systemd_docker_socket

    # Docker daemon command line docs
    # https://docs.docker.com/engine/reference/commandline/dockerd/
    - name: "Install dockerd daemon.json with TLS enabled"
      template:
        src: daemon.json.j2
        dest: "/etc/docker/daemon.json"
      register: dockerd_conf

    - name: "Restart docker service to pick up TLS configuration"
      systemd:
        name: docker.service
        daemon_reload: yes
        state: restarted
      when:
        systemd_docker_socket.changed or certmonger_certs_changed
        

  become: true
  tags: dockerd-tls
