---
############################################
# Write latest /etc/hosts on remote host

- block:

    - name: "Template /etc/hosts"
      template:
        src: etc-hosts.j2
        dest: /etc/hosts
      become: true
