---
############################################
# Write latest /etc/hosts on remote host

- block:

    - name: "Get DigitalOcean inventory"
      do_droplet_info:
        names: "{{ groups.digitalocean|formatmaplist('{}.%s' % domain_name)}}"
        api_token:  "{{ digitalocean_token }}"
      register: droplet_info

    - name: "Template /etc/hosts"
      template:
        src: etc-hosts.j2
        dest: /etc/hosts
      become: true
