---
# Label and partition disk

# Example playbook entry
#
# - role: disk-label
#   volume_name: myvol
#   device:  /dev/disk/by-id/myvol
#   # label default gpt
#   # align default optimal
#   partitions:
#     - number: 1
#       fs_type:  linux-swap
#       # part_start default 0
#       part_end:  1GiB
#     - number: 2
#       # fs_type default ext4
#       part_start:  1GiB
#       # part_end default 100%

##############################
# Label volume

- name: "Collect volume info"
  parted:
    device: "{{ item }}"
    state: info
    unit: GiB
  with_items:
    - "{{ device }}"
  become: true
  register: parted_info
  tags:
    - setup

- name: debug volume info
  debug:
    var: parted_info
    verbosity: 1
  tags:
    - setup

- name: "Create device volume label"
  parted:
    device: "{{ item.device }}"
    label: "{{ item.label }}"
    state: present
    unit: GiB
  with_items:
    - device: "{{ device }}"
      label: "{{ label|default('gpt') }}"
  become: true
  register: parted_label
  when: parted_info.results.0.disk.table == 'unknown'
  tags:
    - setup

- name: debug data volume label
  debug:
    var: parted_label
    verbosity: 1
  tags:
    - setup


##############################
# Create partitions

- name: "Create partition on device"
  parted:
    align: "{{ align|default('optimal') }}"
    device: "{{ device }}"
    number: "{{ item.number }}"
    state: present
    part_type: "{{ item.part_type|default('primary') }}"
    fs_type: "{{ item.fs_type|default('ext4') }}"
    part_start: "{{ item.part_start|default('0%') }}"
    part_end: "{{ item.part_end|default('100%') }}"
    unit: GiB
  become: true
  register: create_partition
  with_items:  "{{ partitions }}"
  tags:
    - setup

# - name: debug create partition
#   debug:
#     var: create_partition
