---
# Partition disk
#
# Called from main.yaml, once for each partition
#
# May set these parted mkpart options:
#   partition.number:  1...
#   partition.part_type:  default primary
#   partition.fs_type:  default ext4; linux-swap, ...
#   partition.part_start: default 0
#   partition.part_end:  default 100%

# - name: Debug create partition inputs
#   debug:
#     var: partition

- name: "Device {{device}}, create partition {{partition.number}}"
  parted:
    align: "{{ align|default('optimal') }}"
    device: "{{ device }}"
    number: "{{ partition.number }}"
    state: present
    part_type: "{{ partition.part_type|default('primary') }}"
    fs_type: "{{ partition.fs_type|default('ext4') }}"
    part_start: "{{ partition.part_start|default('0%') }}"
    part_end: "{{ partition.part_end|default('100%') }}"
    unit: GiB
  become: true
  register: create_partition

- name: Gather facts
  set_fact:
    partition_map: "{{partition_map|combine(
                { '%s_%d'%(volume_name, partition.number):create_partition })}}"

# - name: debug create partition
#   debug:
#     var: create_partition

