---
# Install and configure etcd3 and kubernetes on CoreOS

############################################
- name: Install CoreOS cluster
  hosts: coreos

  roles:

    # Set up etcd3
    - role: etcd3-bootstrap
      tags: etcd3

    # Set up flannel
    - role: flannel-bootstrap
      tags: flannel

    # Set up kubernetes
    - role: kubernetes-bootstrap
      tags: kubernetes

    # Add ipa and ipaclient containers to kubernetes
