---
# Set up clustering on CoreOS

############################################
- name: Install CoreOS cluster
  hosts: coreos
  # FIXME WTF?  Suddenly needed why?
  environment:
    PYTHONPATH: "../lib/python"

  roles:

    # Configure CoreOS Docker TLS
    - role: docker-tls
      tags: docker-tls

    # Set up etcd
    - role: etcd3-bootstrap
      tags: etcd

    # Set up flannel
    - role: flannel-bootstrap
      tags: flannel
