---
# Set up clustering on CoreOS

############################################
- name: Install CoreOS cluster
  hosts: coreos

  roles:

    # Set up etcd
    - role: etcd3-bootstrap
      tags: etcd

    # Set up flannel
    - role: flannel-bootstrap
      tags: flannel

    # Set up kubernetes
    - role: kubernetes-bootstrap
      tags: kubernetes

    # Add ipa and ipaclient containers to kubernetes
