---
# Install and configure etcd3 and kubernetes on CoreOS

############################################
- name: Install etcd3 cluster
  hosts: coreos

  roles:

    # Set up etcd3
    - role: etcd3-bootstrap
      tags: etcd3

    # Set up flannel
    - role: flannel-bootstrap
      tags: flannel


############################################
- name: Install Kubernetes cluster
  hosts: coreos

  roles:

    # Set up kubernetes

############################################
- name: Add FreeIPA to Kubernetes
  hosts: coreos

  roles:

    # Add ipa and ipaclient containers to kubernetes
