---
# Provision FreeIPA in Docker

############################################
- name: Provision FreeIPA in Docker
  hosts: freeipa

  vars:
    ansible_python_interpreter: /home/core/bin/python

  environment:
    # Path for python
    PATH: "/usr/sbin:/usr/bin:/home/core/bin:/bin:/sbin"

  roles:
    # Create and attach block storage
    - role: digitalocean-block-storage
      volume_name: "{{freeipa_block_storage_name}}"
      volume_size: "{{freeipa_volume_size}}"
      tags: freeipa-volume

    # Label and partition block device
    - role: disk-label
      volume_name: freeipa
      device: "{{freeipa_volume_block_device}}"
      partitions:
        - number: 1
      tags: freeipa-volume

    # Make ext4 fs on data partition and install+start systemd mount
    # service
    - role: mkfs-ext4
      device: "{{freeipa_volume_device}}"
      mount_path: "{{freeipa_volume_path}}"
      tags: freeipa-volume

    # Install FreeIPA in Docker container
    - role: freeipa-install
      tags: freeipa-install

    # Configure FreeIPA:  hardening, http, DNS, CA
    - role: freeipa-configure
      tags:
        - freeipa-install
        - freeipa-configure

    # Configure CoreOS Docker:  SSL CA, server and client certs
    - role: bootstrap-user
      tags:
        - freeipa-install
        - freeipa-bootstrap-user

    # Install FreeIPA client
    - role: freeipa-client-install
      tags:
        - freeipa-install
        - freeipa-client-install
