---
# Provision FreeIPA in Docker

############################################
- name: Provision FreeIPA in Docker
  hosts: freeipa
  # FIXME WTF?  Suddenly needed why?
  environment:
    PYTHONPATH: "../lib/python"

  roles:
    # Create and attach block storage
    - role: digitalocean-block-storage
      volume_name: "{{freeipa_block_storage_name}}"
      volume_size: "{{freeipa_volume_size}}"
      tags: freeipa-volume

    # Label and partition block device
    - role: disk-label
      volume_name: freeipa
      device: "{{freeipa_volume_block_device}}"
      partitions:
        - number: 1
      tags: freeipa-volume

    # Make ext4 fs on data partition and install+start systemd mount
    # service
    - role: mkfs-ext4
      device: "{{freeipa_volume_device}}"
      mount_path: "{{freeipa_volume_path}}"
      tags: freeipa-volume

    # Install FreeIPA server in Docker container
    # - Initial IPA server is installed before IPA configuration
    - role: freeipa-install
      tags: freeipa-install

    # IPA settings for http, DNS, CA, LDAP
    - role: freeipa-configure
      tags: freeipa-configure
