---
- name: Initialize ansible
  hosts: localhost
  connection: local
  # Don't run setup on localhost
  gather_facts: False

  vars_prompt:
  - name: freeipa_admin_password
    prompt: Please enter the FreeIPA admin pass
    private: yes

  - name: freeipa_ds_password
    prompt: Please enter the FreeIPA ds pass
    private: yes

  roles:
    # Create encrypted FreeIPA password vault
    - role: vault
