---
# Set up Kubernetes

############################################
- name: Install Kubernetes cluster
  hosts: coreos
  # FIXME WTF?  Suddenly needed why?
  environment:
    PYTHONPATH: "../lib/python"

  roles:

    # Set up kubernetes
    - role: kubernetes-bootstrap
      tags: kubernetes
