---
# Provision DigitalOcean hosts

############################################
- name: Create DigitalOcean droplets and block storage
  hosts: coreos
  # This all runs on localhost regardless of whether hosts exist;
  # don't run setup
  gather_facts: False
  connection: local

  roles:
    # Generate cloud-config for next step
    - role: coreos-cloud-config
      tags: create-droplet

    # Create DigitalOcean droplet
    - role: digitalocean-droplet-create
      tags: create-droplet

    # Update /etc/hosts with new droplet
    - role: local-etc-hosts
      tags: create-droplet

    # Create data volume
    - role: digitalocean-block-storage
      volume_name: "{{data_volume_name}}"
      volume_size: "{{data_volume_size}}"
      tags: create-droplet

############################################
- name: Bootstrap ansible on CoreOS
  hosts: coreos
  # No python on host yet; don't run setup
  gather_facts: False

  environment:
    # Path for python utilities from defunctzombie.coreos-bootstrap
    PATH: "/usr/sbin:/usr/bin:/home/core/bin"

  roles:
    # Install python and modules needed by Ansible
    - role: defunctzombie.coreos-bootstrap
      tags: coreos-bootstrap-python

    - role: coreos-ansible
      tags: coreos-bootstrap-python

############################################
- name: Configure CoreOS block storage
  hosts: coreos

  roles:
    # Partition attached disks
    - role: disk-label
      volume_name: data
      device: "{{data_volume_block_device}}"
      partitions:
        - number: 1
          fs_type:  linux-swap
          part_end:  "{{ swap_size }}GiB"
        - number: 2
          part_start:  "{{ swap_size }}GiB"
      tags: data-volume

    # Set up swap on `swap_device`
    - role: swap
      tags: data-volume

    # Set up ext4 fs on data partition
    - role: mkfs-ext4
      device: "{{data_volume_device}}"
      mount_path: "{{data_volume_path}}"
      tags: data-volume
