---
# Provision DigitalOcean hosts

############################################
- name: Create DigitalOcean droplets and block storage
  hosts: coreos
  # This all runs on localhost regardless of whether hosts exist;
  # don't run setup
  gather_facts: False
  connection: local

  roles:
    # Generate cloud-config for next step
    - role: coreos-cloud-config
      tags: coreos-cloud-config

    # Create DigitalOcean droplets
    - role: digitalocean-droplet-create
      tags: digitalocean

############################################
- name: Bootstrap ansible on CoreOS
  hosts: coreos
  # No python on host yet; don't run setup
  gather_facts: False
  vars:
     ansible_python_interpreter: /home/core/bin/python

  environment:
    # Path for python
    PATH: "/usr/sbin:/usr/bin:/home/core/bin"

  roles:
    # Update /etc/hosts with new droplets
    - role: local-etc-hosts
      tags: local-etc-hosts

    # Install python and modules needed by Ansible
    - role: defunctzombie.coreos-bootstrap
      tags: coreos-bootstrap-python

    - role: coreos-ansible
      tags: coreos-ansible

############################################
- name: Configure CoreOS block storage
  hosts: coreos

  vars:
    ansible_python_interpreter: /home/core/bin/python

  environment:
    # Path for python
    PATH: "/usr/sbin:/usr/bin:/home/core/bin"

  roles:
    # Partition attached disks
    - role: disk-label
      volume_name: data
      device: "{{data_volume_block_device}}"
      partitions:
        - number: 1
          fs_type:  linux-swap
          part_end:  "{{ swap_size }}GiB"
        - number: 2
          part_start:  "{{ swap_size }}GiB"
      tags: disk-label

    # Set up swap on `swap_device`
    - role: swap
      tags: swap

    # Set up ext4 fs on data partition
    - role: mkfs-ext4
      device: "{{data_volume_device}}"
      mount_path: "{{data_volume_path}}"
      tags: data-volume
