---
# Install everything in the right order


# 1.  Provision CoreOS host on DigitalOcean
- include: provision.yaml
  tags:  provision

# 2.  Install FreeIPA in Docker
- include: freeipa.yaml
  tags:  freeipa

# 3.  Install docker TLS, etcd, flanneld, kubernetes
- include: cluster.yaml
  tags:  cluster

# 4.  Install services
- include: services.yaml
  tags:  services
